### ISSUE TITLE
Upgrade Web APIs and schemata

### ISSUE THREAD

**Issue by izumin5210** [izumin5210/actopus#35]
:page_facing_up: [API document](https://github.com/izumin5210/actopus/blob/master/doc/api.md) ([staging](http://actopus.herokuapp.com/docs))
# TODO
- [ ] access token（現状だとそもそもoauthいらない？）
- [ ] lectures from the class
- [ ] lectures from the lecturer
- [ ] lecturers
- [ ] reschedulings from the class
- [ ] reschedulings from the lecturer

**Comment by ismail-a** [comment]
@izumin5210 
時間割XMLのスキーマ案（変更後）ってどこかにありますか？
色々と変更・追加したい内容は#6で議論していましたが、まとまったやつが見つからない・・・

**Comment by ismail-a** [comment]
@izumin5210 @yamasy1549 

とりあえず、#6の議論を追ってみて、学務システムのxlsファイルから新フォーマットのXMLを自動生成するスクリプトを作成しました。
出力結果を以下に置いておきます。
http://ubi-www.akashi.ac.jp/~ismail/tmp/timetable201504.xml

電気の4、5年のデータが何故かxlsファイルにないので、明日にでも教務係に確認します。
いくらか気になる点があるけど、対応しようとすると手入力が必要になって大変なのでこれくらいにしておきたいです。
・使用教室の情報が学務システムに入っていない
・教員名が姓しか入っていない
・男子体育と女子体育は学務システムのデータ上では科目名に区別がない
　・女子体育は科目IDの末尾に"B"という文字が入っているので機械的にSpecialTargetを指定できた
　・一応例外処理で科目名の区別はできます
・留学生科目であることを判別するデータがないので「日本語」を例外的に対応

他、何か抜けている点があったらいってください。

**Comment by izumin5210** [comment]
@ismail-a 
確認しました
ありがとうございます！
